#!/usr/bin/env python3
"""Generate the customer portal's static pages from content/*.py.

    python3 tools/build_site.py

Each section module in content/ exports `content`: one section's HTML (plus its
own <style>/<script>). This script wraps every section in the shared page shell
(nav, search, language dialog, footer) and writes it to its own URL:

    site/customer/index.html               <- content/welcome.py
    site/customer/products/index.html      <- content/products.py
    ...
    site/customer/search-index.json        <- headings + item titles, for search

The output is GENERATED - edit content/*.py or the shell below, then rebuild.
deploy.sh runs this automatically before every deploy. Everything under
/customer/ (pages AND the search index) is gated by functions/customer/_middleware.js.
"""
import hashlib
import html as htmllib
import importlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
sys.path.insert(0, str(ROOT / "content"))

# (id used by switchTab, module, URL, nav label, eyebrow, icon)
SECTIONS = [
    ("welcome", "welcome", "/customer/", "Welcome", "Start here", "fa-house"),
    ("products", "products", "/customer/products/", "My Products", "Your hardware", "fa-box-open"),
    ("installation", "installation", "/customer/installation/", "Installation", "Get vehicles online", "fa-screwdriver-wrench"),
    ("platform", "platform_tutorials", "/customer/platform/", "Platform Tutorials", "Learn the platform", "fa-display"),
    ("ai-features", "ai_features", "/customer/ai-features/", "AI Features", "AI safety", "fa-brain"),
    ("training", "training_academy", "/customer/training/", "Training Academy", "Team enablement", "fa-graduation-cap"),
    ("playbooks", "playbooks", "/customer/playbooks/", "Playbooks", "Run the programme", "fa-book-open"),
    ("support", "support", "/customer/support/", "Support", "Get help", "fa-life-ring"),
]
ROUTE = {s[0]: s[2] for s in SECTIONS}

GENERATED_NOTE = "<!-- GENERATED by tools/build_site.py from content/*.py - do not edit by hand. -->"

# Item titles worth finding by name, beyond h2-h4 headings.
SEARCH_ITEM_CLASSES = ("product-name", "inst-prod-name", "aif-feat-name", "pfn-name", "video-title")


def asset_version(rel: str) -> str:
    """Short content hash for cache-busting (?v=...)."""
    return hashlib.sha1((SITE / rel.lstrip("/")).read_bytes()).hexdigest()[:10]


def strip_tags(s: str) -> str:
    s = re.sub(r"<(style|script)\b.*?</\1>", " ", s, flags=re.S)
    s = re.sub(r"<[^>]+>", " ", s)
    return re.sub(r"\s+", " ", htmllib.unescape(s)).strip()


def slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s[:60] or "section"


def rewrite_nav_links(html: str) -> str:
    """href="javascript:void(0)" onclick="switchTab('x')" -> real href. Real links fix
    back/refresh/middle-click and the Chrome/Windows javascript:void(0) failure."""
    def repl(m):
        url = ROUTE.get(m.group(1))
        if not url:
            raise SystemExit(f"build_site: unknown switchTab target {m.group(1)!r}")
        return f'href="{url}"'
    return re.sub(r'href="javascript:void\(0\)"\s+onclick="switchTab\(\'([a-z-]+)\'\)"', repl, html)


def promote_page_title(html: str, eyebrow: str) -> str:
    """The first <h2> of a section page is its title: make it the page's only <h1>
    (heading hierarchy) and put the eyebrow above it."""
    m = re.search(r"<h2(\s[^>]*)?>(.*?)</h2>", html, flags=re.S)
    if not m:
        return html
    h1 = f'<p class="page-eyebrow">{eyebrow}</p><h1 class="page-title">{m.group(2)}</h1>'
    return html[: m.start()] + h1 + html[m.end():]


def excluded_spans(html: str):
    """Regions not indexed for search (the FleetMind simulator's own UI)."""
    spans = []
    for m in re.finditer(r"<!-- simulator -->(.*?)<!-- /simulator -->", html, flags=re.S):
        spans.append((m.start(), m.end()))
    for m in re.finditer(r'<section class="stmx-brand-morph".*?</section>', html, flags=re.S):
        spans.append((m.start(), m.end()))  # the Welcome particle band (decorative copy)
    return spans


def add_anchors_and_index(html: str, sid: str, label: str, url: str, icon: str):
    """Give every heading / item title an id (if it lacks one) and collect search entries."""
    entries = []
    used = set(re.findall(r'\sid="([^"]+)"', html))
    skip = excluded_spans(html)
    item_re = "|".join(SEARCH_ITEM_CLASSES)
    pattern = re.compile(
        r'<(h[1-4])(\s[^>]*)?>(.*?)</\1>'
        r'|<(span|div|strong)(\s[^>]*class="[^"]*\b(?:' + item_re + r')\b[^"]*"[^>]*)>(.*?)</\4>',
        flags=re.S,
    )
    out, pos = [], 0
    for m in pattern.finditer(html):
        if any(a <= m.start() < b for a, b in skip):
            continue
        tag = m.group(1) or m.group(4)
        attrs = (m.group(2) if m.group(1) else m.group(5)) or ""
        inner = m.group(3) if m.group(1) else m.group(6)
        title = strip_tags(inner)
        if not title or len(title) < 3:
            continue
        idm = re.search(r'\sid="([^"]+)"', attrs)
        if idm:
            anchor = idm.group(1)
            new_open = f"<{tag}{attrs}>"
        else:
            base = slugify(title)
            anchor, n = base, 2
            while anchor in used:
                anchor, n = f"{base}-{n}", n + 1
            used.add(anchor)
            new_open = f'<{tag} id="{anchor}"{attrs}>'
        out.append(html[pos:m.start()])
        out.append(new_open + inner + f"</{tag}>")
        pos = m.end()
        snippet = strip_tags(html[m.end(): m.end() + 900])[:160]
        entries.append({
            "t": title[:120],
            "s": label,
            "u": url if tag == "h1" else f"{url}#{anchor}",
            "x": snippet,
            "i": icon,
        })
    out.append(html[pos:])
    return "".join(out), entries


def nav_html(active: str) -> str:
    links = "".join(
        f'<a class="nav-btn{" active" if sid == active else ""}" href="{url}"'
        f'{" aria-current=\"page\"" if sid == active else ""}>{label}</a>'
        for sid, _m, url, label, _e, _i in SECTIONS
    )
    drawer = "".join(
        f'<a href="{url}"{" class=\"active\" aria-current=\"page\"" if sid == active else ""}>'
        f'<i class="fa-solid {icon}" aria-hidden="true"></i><span>{label}</span></a>'
        for sid, _m, url, label, _e, icon in SECTIONS
    )
    return f"""
    <header class="nav-tabs">
        <div class="nav-inner">
            <a class="nav-brand" href="/customer/" translate="no">
                <img src="/assets/img/streamax-logo.png" alt="Streamax" width="118" height="14">
            </a>
            <nav class="nav-links" aria-label="Portal sections">{links}</nav>
            <div class="nav-tools">
                <button class="nav-search" type="button" data-open-search aria-label="Search the portal" aria-keyshortcuts="Control+K Meta+K">
                    <i class="fa-solid fa-magnifying-glass" aria-hidden="true"></i><span>Search</span><kbd>Ctrl K</kbd>
                </button>
                <button class="nav-menu-btn" type="button" id="nav-menu-btn" aria-expanded="false" aria-controls="nav-drawer" aria-label="Open section menu">
                    <i class="fa-solid fa-bars" aria-hidden="true"></i><span>Menu</span>
                </button>
                <div class="nav-user" id="nav-user">
                    <button class="user-trigger" type="button" onclick="toggleUserMenu(event)" aria-haspopup="true" aria-expanded="false">
                        <span class="user-avatar"><i class="fa-solid fa-building" aria-hidden="true"></i></span>
                        <span class="user-name" data-slot="identity"></span>
                        <i class="fa-solid fa-chevron-down user-chevron" aria-hidden="true"></i>
                    </button>
                    <div class="user-dropdown" id="user-dropdown" role="menu">
                        <div class="ud-header">
                            <div class="ud-name" data-slot="identity"></div>
                            <div class="ud-tag" data-slot="audience"></div>
                        </div>
                        <button class="ud-item" type="button" role="menuitem" onclick="openLangModal()" translate="no">
                            <i class="fa-solid fa-globe" aria-hidden="true"></i><span>Language</span>
                            <span class="ud-current" id="ud-current-lang">English</span>
                        </button>
                        <a class="ud-item" role="menuitem" href="/customer/support/">
                            <i class="fa-solid fa-life-ring" aria-hidden="true"></i><span>Help &amp; support</span>
                        </a>
                        <div class="ud-sep" role="separator"></div>
                        <a class="ud-item ud-signout" role="menuitem" href="/customer/login/" onclick="return signOut(event)" translate="no">
                            <i class="fa-solid fa-right-from-bracket" aria-hidden="true"></i><span>Sign out</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <nav class="nav-drawer" id="nav-drawer" aria-label="Portal sections">{drawer}</nav>"""


SEARCH_DIALOG = """
    <div class="scrim search-scrim" id="search-dialog" hidden>
        <div class="dialog search-dialog" role="dialog" aria-modal="true" aria-label="Search the portal">
            <div class="search-field">
                <i class="fa-solid fa-magnifying-glass" aria-hidden="true"></i>
                <input id="search-input" type="search" placeholder="Search products, install guides, AI features..."
                       autocomplete="off" spellcheck="false" role="combobox" aria-expanded="true"
                       aria-controls="search-results" aria-autocomplete="list">
                <kbd class="search-esc">Esc</kbd>
            </div>
            <ul class="search-results" id="search-results" role="listbox" aria-label="Results"></ul>
            <div class="search-foot" aria-hidden="true"><span><kbd>&uarr;</kbd> <kbd>&darr;</kbd> to move</span><span><kbd>Enter</kbd> to open</span></div>
        </div>
    </div>"""

LANG_MODAL = """
    <div class="lang-overlay" id="lang-overlay" onclick="if (event.target === this) closeLangModal()">
        <div class="lang-modal" translate="no" role="dialog" aria-modal="true" aria-labelledby="lang-title">
            <button class="lang-modal-close" type="button" onclick="closeLangModal()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
            <h3 id="lang-title">Choose your language</h3>
            <p class="lang-sub">The portal switches instantly, no reload needed.</p>
            <div class="lang-grid">
                <button class="lang-card selected" type="button" data-lang="en" onclick="selectLanguage('en', this)">
                    <span class="lang-flag">EN</span><span class="lang-meta"><span class="lang-label">English</span><span class="lang-native">Default</span></span>
                    <i class="fa-solid fa-circle-check lang-check" aria-hidden="true"></i></button>
                <button class="lang-card" type="button" data-lang="es" onclick="selectLanguage('es', this)">
                    <span class="lang-flag">ES</span><span class="lang-meta"><span class="lang-label">Spanish</span><span class="lang-native">Español</span></span>
                    <i class="fa-solid fa-circle-check lang-check" aria-hidden="true"></i></button>
                <button class="lang-card" type="button" data-lang="pt" onclick="selectLanguage('pt', this)">
                    <span class="lang-flag">PT</span><span class="lang-meta"><span class="lang-label">Portuguese</span><span class="lang-native">Português</span></span>
                    <i class="fa-solid fa-circle-check lang-check" aria-hidden="true"></i></button>
                <button class="lang-card" type="button" data-lang="fr" onclick="selectLanguage('fr', this)">
                    <span class="lang-flag">FR</span><span class="lang-meta"><span class="lang-label">French</span><span class="lang-native">Français</span></span>
                    <i class="fa-solid fa-circle-check lang-check" aria-hidden="true"></i></button>
            </div>
        </div>
    </div>
    <div id="google_translate_element"></div>"""


def pager_html(index: int) -> str:
    prev_s = SECTIONS[index - 1] if index > 0 else None
    next_s = SECTIONS[index + 1] if index + 1 < len(SECTIONS) else None
    def card(s, rel):
        if not s:
            return "<span></span>"
        arrow_l = '<i class="fa-solid fa-arrow-left" aria-hidden="true"></i>' if rel == "prev" else ""
        arrow_r = '<i class="fa-solid fa-arrow-right" aria-hidden="true"></i>' if rel == "next" else ""
        cap = "Previous" if rel == "prev" else "Next"
        return (f'<a class="pager-link pager-{rel}" href="{s[2]}" rel="{rel}">'
                f'<span class="pager-cap">{arrow_l}{cap}</span><span class="pager-title">{s[3]}</span>{arrow_r}</a>')
    return f'<nav class="pager" aria-label="Previous and next section">{card(prev_s, "prev")}{card(next_s, "next")}</nav>'


FOOTER = """
    <footer class="site-foot">
        <div class="site-foot-inner">
            <span>&copy; Streamax Technology. Customer onboarding portal.</span>
            <span class="site-foot-links">
                <a href="/customer/support/">Support</a>
                <a href="mailto:support@streamax.com">support@streamax.com</a>
                <a href="https://www.streamax.com" rel="noopener">streamax.com</a>
            </span>
        </div>
    </footer>"""


def page_html(section_id: str, title: str, body: str, index: int, v: dict) -> str:
    return f"""<!DOCTYPE html>
{GENERATED_NOTE}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex, nofollow">
    <meta name="theme-color" content="#ffffff">
    <title>{title} - Streamax Customer Onboarding</title>
    <script>document.documentElement.classList.add('js-reveal');</script>
    <link rel="icon" type="image/svg+xml" href="/assets/img/favicon.svg">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="/assets/css/stx.css?v={v['stx']}">
    <link rel="stylesheet" href="/assets/css/portal.css?v={v['portal_css']}">
</head>
<body data-section="{section_id}">
    <a class="skip-link" href="#main">Skip to content</a>
{nav_html(section_id)}
{SEARCH_DIALOG}
{LANG_MODAL}

    <main class="container" id="main" tabindex="-1">
{body}
        {pager_html(index)}
    </main>
{FOOTER}

    <script src="/assets/js/portal.js?v={v['portal_js']}"></script>
    <script src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit" async></script>
</body>
</html>
"""


def build() -> int:
    v = {
        "stx": asset_version("/assets/css/stx.css"),
        "portal_css": asset_version("/assets/css/portal.css"),
        "portal_js": asset_version("/assets/js/portal.js"),
    }
    morph_v = asset_version("/assets/morph/truck-to-logo.html")
    index = []
    for i, (sid, module, url, label, eyebrow, icon) in enumerate(SECTIONS):
        html = importlib.import_module(module).content
        html = html.replace('class="content-section hidden"', 'class="content-section"')
        html = rewrite_nav_links(html)
        if sid == "welcome":
            # Extensionless: Pages 308-redirects *.html, which would drop the ?v= cache-buster.
            html = html.replace("__TRUCK_TO_LOGO_SRC__", f"/assets/morph/truck-to-logo?v={morph_v}")
            html = html.replace(
                "__KEY_CONTACTS__",
                '<tbody data-slot="contacts"><tr><td colspan="2">Loading your Streamax team...</td></tr></tbody>',
            )
        else:
            html = promote_page_title(html, eyebrow)
        html, entries = add_anchors_and_index(html, sid, label, url, icon)
        index.append({"t": label, "s": "Portal section", "u": url, "x": eyebrow, "i": icon})
        index.extend(e for e in entries if e["t"].lower() != label.lower())
        left = sorted(set(re.findall(r"__[A-Z][A-Z_]+__", html)))
        if left:
            raise SystemExit(f"build_site: unresolved placeholders in {module}: {left}")
        if "javascript:void" in html:
            raise SystemExit(f"build_site: javascript:void link left in {module}")
        out = SITE / url.lstrip("/") / "index.html"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(page_html(sid, label, html, i, v), encoding="utf-8")
        print(f"  {url:28s} <- content/{module}.py  ({out.stat().st_size // 1024} KB, {len(entries)} search entries)")
    (SITE / "customer" / "search-index.json").write_text(
        json.dumps(index, ensure_ascii=False, separators=(",", ":")), encoding="utf-8"
    )
    print(f"  /customer/search-index.json  ({len(index)} entries)")
    return len(SECTIONS)


if __name__ == "__main__":
    n = build()
    print(f"build_site: wrote {n} customer pages")
